globex-ui:
  image:
    repository: quay.io/globex-recommendation/globex-recommendation-ui
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "68549ea"

  route:
    enabled: true

  activityTrackingService:
    name: activity-tracking
    url: http://activity-tracking:8080
    postActivityPath: /track
  catalogService:
    name: catalog
    url: http://catalog:8080
    getProductsPath: /services/products
    getProductListPath: /services/product/list/
  recommendationEngine:
    name: recommendation-engine
    url: http://recommendation-engine:8080
    getRecommendedProductsPath: /score/product 
  orderPlacementService:
    name: order-placement
    url: http://order-placement:8080
    postOrderPath: /placeorder
