apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: activity-tracking-externalsecret
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: activity-tracking
    template:
      engineVersion: v2
      templateFrom:
      - secret:
          # name of the configmap to pull in
          name: activity-tracking
          # here you define the keys that should be used as template
          items:
          - key: application.properties
  data:
  - secretKey: kafkaBootstrapServer
    remoteRef:
      key: secret/data/hub/kafka
      property: bootstrapserver
  - secretKey: kafkaUserId
    remoteRef:
      key: secret/data/hub/kafka
      property: userid
  - secretKey: kafkaPassword
    remoteRef:
      key: secret/data/hub/kafka
      property: password
