recommendation-engine:
  image:
    repository: quay.io/globex-recommendation/recommendation-engine
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "3ee6286"

  kafka:
    bootstrapServer: "{{ .kafkaBootstrapServer }}"
    securityProtocol: SASL_SSL
    saslMechanism: PLAIN
    userId: "{{ .kafkaUserId }}"
    password: "{{ .kafkaPassword }}"
    streams:
      topics: globex.tracking
      replicationFactor: 1
      commitIntervalMs: 10000
      applicationId: globex.recommendation
    topics:
      trackingEvent: globex.tracking